baseURL = "https://knowledged.to/"
languageCode = "en-us"
title = "knowledged.to"
theme = "PaperMod"
enableRobotsTXT = true

ignoreLogs = ['warning-goldmark-raw-html']

[pagination]
  pagerSize = 20

[params]
  homepageMode = "posts"
  mainSections = ["notes", "ai"]
  ShowReadingTime = true
  ShowShareButtons = false
  ShowCodeCopyButtons = true
  ShowToc = true
  defaultTheme = "auto"

[outputs]
  home = ["HTML", "RSS", "JSON"]
